version: '3.8'

services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db
      DATABASE_URL: postgresql+psycopg://${DB_USER}:${DB_PASS}@db:${DB_PORT}/${DB_NAME}
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "5173:80"
    environment:
      VITE_API_BASE_URL: "http://localhost:8000"

volumes:
  db_data:
